### ISSUE TITLE
Interesting experiment!

### ISSUE THREAD

**Issue by FGRibreau** [fastnsilver/xlator#1]
Very interesting experiment @fastnsilver :)

Even if it's still a work in progress, this translation library will be shared in our next [RedisWeekly](http://redisweekly.com/)! Once published (in a matter of minutes) you will be able to see your [projet description here](http://redisweekly.com/archive/138.html) :)

**Comment by fastnsilver** [comment]
I've completed much of what I wanted to explore in this prototype. I've also published a Docker image to Dockerhub.  I authored a couple of scripts for provisioning and deploying a Docker Compose cluster via ECS CLI to AWS.  And I also authored a docker-compose.yml that includes an instance of Redis that acts as the cache provider.  If anyone is interested in this work (or alternate paths) drop me a line.

**Comment by FGRibreau** [comment]
:+1:
